### ISSUE TITLE
sass-loader 12.3.0 breaks compatibility with thread-loader

### ISSUE THREAD

**Issue by AprilArcus** [webpack-contrib/sass-loader#1016]
The introduction of webpack logging in sass-loader@12.3.0 (https://github.com/webpack-contrib/sass-loader/pull/991) causes the loader to fail when used in conjunction with [thread-loader](https://github.com/webpack-contrib/thread-loader), as loaders running behind thread-loader cannot access webpack loader options.

```
$HOME/project/node_modules/sass-loader/dist/utils.js:209
    const logger = loaderContext.getLogger("sass-loader");
                                 ^

TypeError: loaderContext.getLogger is not a function
    at getSassOptions ($HOME/project/node_modules/sass-loader/dist/utils.js:209:34)
    at Object.loader ($HOME/project/node_modules/sass-loader/dist/index.js:35:55)
    at LOADER_EXECUTION ($HOME/project/node_modules/loader-runner/lib/LoaderRunner.js:132:14)
    at runSyncOrAsync ($HOME/project/node_modules/loader-runner/lib/LoaderRunner.js:133:4)
    at iterateNormalLoaders ($HOME/project/node_modules/loader-runner/lib/LoaderRunner.js:250:2)
    at $HOME/project/node_modules/loader-runner/lib/LoaderRunner.js:223:4
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)
node:events:368
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at Pipe.onStreamRead (node:internal/stream_base_commons:220:20)
Emitted 'error' event on Socket instance at:
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -104,
  code: 'ECONNRESET',
  syscall: 'read'
}
```

**Comment by alexander-akait** [comment]
Known bug in thread-loader, let's keep open this in thread-loader, we can't fix it here

**Comment by AprilArcus** [comment]
I disagree; this could be easily resolved by offering an option in sass-loader to disable logging.

**Comment by alexander-akait** [comment]
We should not disable logging due problems in other place, we should fix the root of a problem

**Comment by alexander-akait** [comment]
You can send a fix in thread-loader and I will review it

**Comment by mihanizm56** [comment]
```
    "sass-loader": "13.0.2",
    "thread-loader": "3.0.4",
```

still the same error with recommended options in webpack 5 docs

```
        {
          loader: "thread-loader",
          options: {
            workerParallelJobs: 2,
          },
        },
```

**Comment by yuanhongboo** [comment]
Solved! Here's the code:
```js
{
  loader: 'sass-loader',
  options: {
    sassOptions: {
      logger: console, // HACK 
    },
  },
}
```

**Comment by mihanizm56** [comment]
@yuanhongboo still not working for me. my config is on the picture. maybe this problem is connected with css-loader/css-modules

![image](https://github.com/webpack-contrib/sass-loader/assets/37120827/ba9c6bf7-ef68-4b9a-a9d5-630d667d66a7)

![image](https://github.com/webpack-contrib/sass-loader/assets/37120827/b860f756-ebba-45bb-9a9a-498af2461c8b)
