### ISSUE TITLE
TypeError: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by halt-hammerzeit** [webpack-contrib/sass-loader#373]
When using Webpack 2.

See the original issue for the explanation and my workaround: https://github.com/jtangelder/sass-loader/issues/298

```
path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
```

**Comment by jhnns** [comment]
Sorry, there is not enough information to reproduce this. Please provide a minimal test repository that demonstrates the problem so I can check that out. Try to remove as much stuff as possible since it helps tracking down the problem.

**Comment by halt-hammerzeit** [comment]
Ok, I won't provide a sample repo but other people coming from google can.
This issue is not just mine though, you can see at least 2 other people in the linked issue having the same error.

**Comment by matthieuh** [comment]
I have this issue too using this config with webpack 2 :
```
use: [
  'style-loader',
  {
    loader: 'css-loader',
    options: {
      sourceMap: true
    }
  },
  {
    loader: 'sass-loader',
    options: {
      sourceMap: true
    }
  }
],
```
But uisng just this one it work : 
`use: ['style-loader', 'css-loader', 'sass-loader']`
Maybe an issue link to sourcemaps.

**Comment by matthieuh** [comment]
I get this error too trying to have sourcemap with webpack 2
```
use: [
  'style-loader',
  {
    loader: 'css-loader',
    options: {
      sourceMap: true
    }
  },
  {
    loader: 'sass-loader',
    options: {
      sourceMap: true
    }
  }
]
```

but using just `use: ['style-loader', 'css-loader', 'sass-loader']` it work

Edit:

error :  69% building modules 881/882 modules 1 active ...rkspace/wingz-xxx/src/app/app.scsspath.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));

app.scs line 7 :
```
@font-face {
  font-family: 'Galano Classic';
  font-style: normal;
  font-weight: 400;
  src: url('../assets/fonts/galano/Galano-Classic-Alt.eot');
  src: url('../assets/fonts/galano/Galano-Classic-Alt.eot?#iefix') format('embedded-opentype'),
       url('../assets/fonts/galano/Galano-Classic-Alt.ttf') format('truetype');
}
```

**Comment by jhnns** [comment]
I assume you are using the `LoaderOptionsPlugin`? Could you paste the configuration of that?

This will probably be fixed with the next patch version.

**Comment by DBosley** [comment]
Adding a note here: This problem may be related to empty scss/sass files. I only get the error when the file is empty. Adding `body {}` fixes the error.

**Comment by evilebottnawi** [comment]
@halt-hammerzeit @matthieuh seems we have old `css-loader` (with bugs), just update to latest and try again. If problems still exist please report about this here (be good with minimal reproducible test repo). Thanks!

**Comment by evilebottnawi** [comment]
Fell free to reopen issue if your problem not solved.

**Comment by libbytron** [comment]
I have this same issue....
