### ISSUE TITLE
ERROR in ./node_modules/css-loader!./node_modules/sass-loader/lib/loader.js!./node_modules/extract-text-webpack-plugin/dist/loader.js?

### ISSUE THREAD

**Issue by Maseeharazzack** [webpack-contrib/sass-loader#530]
My code works perfectly in dev environment when I try npm run build I get the following error:

ERROR in ./node_modules/css-loader!./node_modules/sass-loader/lib/loader.js!./node_modules/extract-text-webpack-plugin/dist/loader.js?
{"omit":0,"remove":true}!./node_modules/css-loader!./node_modules/sass-loader/lib/loader.js!./src/app/communication-center/comm-center
.component.scss
Module build failed:
.all-common-grid {
^
Invalid CSS after "e": expected 1 selector or at-rule, was "exports = module.ex"
in D:\dev\Greater_Giving\CommunicationCenter\src\app\communication-center\comm-center.component.scss (line 1, column 1)
@ ./src/app/communication-center/comm-center.component.scss 2:21-317
@ ./src/app/communication-center/comm-center.component.ts
@ ./src/app/communication-center/comm-center.module.ts
@ ./src/app/app-routing.module.ts
@ ./src/app/app.module.ts
@ ./src/app/main.ts

ERROR in ./node_modules/css-loader!./node_modules/sass-loader/lib/loader.js!./node_modules/extract-text-webpack-plugin/dist/loader.js?
{"omit":0,"remove":true}!./node_modules/css-loader!./node_modules/sass-loader/lib/loader.js!./src/assets/style.scss
Module build failed:
/* Imported Stylesheet */
^
Invalid CSS after "e": expected 1 selector or at-rule, was "exports = module.ex"
in D:\dev\Greater_Giving\CommunicationCenter\src\assets\style.scss (line 1, column 1)
@ ./src/assets/style.scss 2:21-286

Following is my code

webpack.config.common.js

var HtmlWebpackPlugin = require('html-webpack-plugin');
var ExtractTextPlugin = require('extract-text-webpack-plugin');
var CopyWebpackPlugin = require('copy-webpack-plugin');
var helpers = require('./helpers');
var webpack = require('webpack');

module.exports = {
entry: {
'app': './src/app/main.ts',
'polyfills': './src/polyfills.ts',
'styles' : './src/assets/style.scss'
},
resolve: {
extensions: ['.ts', '.js']
},
module: {
rules: [
{
test: /.ts$/,
use: [
{
loader: 'awesome-typescript-loader',
options: {
transpileOnly: true
}
},
{ loader: 'angular2-template-loader' },
{ loader: 'angular-router-loader' }
]
},
{
test: /.html$/,
loaders: ['html-loader']
},
{
test: /.scss$/,
exclude: [ /node_modules/, helpers.root('src', 'style.scss') ],
use: [ 'to-string-loader', 'css-loader', 'sass-loader' ]
},
{
test: /.scss$/ ,
use: ExtractTextPlugin.extract({
use: 'css-loader!sass-loader'
})
},
{
test: /.(png|jpe?g|gif|svg|woff|woff2|otf|ttf|eot|ico)$/,
use: 'file-loader?name=assets/[name].[hash].[ext]'
}
],
exprContextCritical: false
},
plugins: [
new ExtractTextPlugin({ // define where to save the file
filename: 'styles/[name].bundle.css',
allChunks: true,
}),
new HtmlWebpackPlugin({
template: 'src/index.html'
}),
new CopyWebpackPlugin([
{
from: 'node_modules/froala-editor/css/',
to: 'assets/froala-editor/css/',
},
{
from: 'node_modules/font-awesome/css/font-awesome.min.css',
to: 'assets/font-awesome/css/font-awesome.min.css',
},
{
from: 'node_modules/font-awesome/fonts',
to: 'assets/font-awesome/fonts'
}
]),
new webpack.ProvidePlugin({
$: "jquery",
jQuery: "jquery"
})
]
};

webpack.config.prod.js
var path = require('path');
var webpack = require('webpack');
var webpackMerge = require('webpack-merge');
var commonConfig = require('./webpack.config.common');
var ExtractTextPlugin = require('extract-text-webpack-plugin');
var UglifyJSPlugin = require('uglifyjs-webpack-plugin');

const ENV = process.env.NODE_ENV = process.env.ENV = 'production';

module.exports = webpackMerge(commonConfig, {
output: {
path: path.resolve(__dirname, 'dist'),
publicPath: '/',
filename: '[name].[hash].js',
chunkFilename: '[id].[hash].chunk.js'
},
plugins: [
new webpack.NoEmitOnErrorsPlugin(),
new webpack.optimize.UglifyJsPlugin({
mangle: {
keep_fnames: true
}
}),
new ExtractTextPlugin('styles.[hash].css'),
new webpack.DefinePlugin({
'process.env': {
'ENV': JSON.stringify(ENV)
}
}),
new webpack.LoaderOptionsPlugin({
options: {
htmlLoader: {
minimize: false // workaround for ng2
}
}
}),
new UglifyJSPlugin()
]
});

**Comment by evilebottnawi** [comment]
@Maseeharazzack not related to `sass-loader` and `css-loader`, please read https://webpack.js.org/guides/getting-started/, seems problem in `to-string-loader` or `ExtractTextPlugin` together with `to-string-loader`. Please provide minimum reproducible test repo.

**Comment by AjayZinngg** [comment]
Re-installing webpack solved the issue for me.
npm install --save-dev webpack

**Comment by juanitaV** [comment]
I have this error : Module build failed (from ./node_modules/sass-loader/lib/loader.js):

**Comment by WebTechnolog** [comment]
@juanitaV try `npm rebuild node-sass`

**Comment by juanitaV** [comment]
@WebTechnolog , thank you! Work for me!

**Comment by dongdongmao** [comment]
`ERROR in ./src/styles.scss (./node_modules/sass-loader/lib/loader.js!./node_modules/css-loader!./src/styles.scss)
Module build failed (from ./node_modules/sass-loader/lib/loader.js):

/* You can add global styles to this file, and also import other style files */
^
      Invalid CSS after "e": expected 1 selector or at-rule, was "exports = module.ex"`

rebuild node-sass and reinstall webpack not work

**Comment by dongdongmao** [comment]
and i run `npm ls node-sass` show 

+-- @angular-devkit/build-angular@0.10.2
| `-- node-sass@4.9.3
`-- node-sass@4.9.4

but if i delete node-sass from my local node_modules then module not found 'node-sass'.  i'm confuse

**Comment by Meetkp001** [comment]
> @juanitaV try `npm rebuild node-sass`

Thanks this is works for me

**Comment by sushantmakin** [comment]
> @juanitaV try `npm rebuild node-sass`

This works for me, but every time I run yarn install to fetch new packages, it again starts giving the same error and I have to rebuild node-sass again. I am using node-sass 4.10.0 and Angular 6.1.0.

**Comment by yosdanybm** [comment]
> @juanitaV try `npm rebuild node-sass`

Thanks this is works for me...

**Comment by Ramyapriya24** [comment]
@juanitaV try npm rebuild node-sass
Thanks a lot this is works for me also ...

**Comment by JohnnyClutch** [comment]
npm rebuild node-sass didnt' work for me.


`ERROR in ./src/scss/application.scss (./node_modules/css-loader!./node_modules/sass-loader/lib/loader.js!./src/scss/application.scss)
Module not found: Error: Can't resolve '../fonts/glyphicons-halflings-regular.eot' in '/Users/gbullock/projects/gadmin-ui/src/scss'
 @ ./src/scss/application.scss (./node_modules/css-loader!./node_modules/sass-loader/lib/loader.js!./src/scss/application.scss) 7:208027-208079 7:208110-208162
 @ ./src/scss/application.scss
 @ ./src/app/app.component.ts
 @ ./src/main.browser.ts
 @ multi (webpack)-dev-server/client?http://localhost:3002 ./src/main.browser.ts`

Anything jump out for anyone?

**Comment by html5ravi** [comment]
npm rebuild node-sass didnt' work for me too. i got error as below

`ERROR in ./src/styles/styles.scss (./node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!./node_modules/postcss-loader/src??embedded!./node_modules/sass-loader/lib/loader.js??ref--14-3!./src/styles/styles.scss)
Module build failed (from ./node_modules/sass-loader/lib/loader.js):

@import '~@pocit/ng-styles/themes/crayola-navy-blue';
@import '~@pocit/ng-styles/styles';

// .mat-dialog-container {
//   padding: 0 !important;
// }

^
      File to import not found or unreadable: ~@pocit/ng-styles/themes/crayola-navy-blue.
      in C:\Users\ra20043636\Downloads\solutionsuite-angular\src\styles\styles.scss (line 1, column 1)
ERROR in projects/ng-components/src/lib/barcode-scanner/dialog/barcode-scanner-dialog.component.ts(14,28): error TS2307: Cannot find module '@pocit/ng-images/general'.
projects/ng-components/src/lib/input-search/input-search.component.ts(17,50): error TS2307: Cannot find module '@pocit/ng-images/general'.
projects/ng-components/src/lib/snack-bar/snack-bar.component.ts(11,42): error TS2307: Cannot find module '@pocit/ng-images/general'.
projects/ng-components/src/lib/top-bar/app-information/app-information.component.ts(15,22): error TS2307: Cannot find module '@pocit/ng-images/general'.
projects/ng-components/src/lib/top-bar/sign-out/change-settings/component/change-settings.component.ts(13,28): error TS2307: Cannot find module '@pocit/ng-images/general'.
projects/ng-components/src/lib/top-bar/tool-bar/tool-bar.component.ts(12,23): error TS2307: Cannot find module '@pocit/ng-images/applications'.
src/app/modules/components/components.component.ts(24,33): error TS2307: Cannot find module '@pocit/ng-images/applications'.`

**Comment by saulwolfcode** [comment]
ERROR in ./src/scss/main.scss (./node_modules/mini-css-extract-plugin/dist/loader.js!./node_modules/css-loader/dist/cjs.js?minimize&sourceMap!./node_modules/postcss-loader/src??ref--6-3!./node_modules/sass-loader/lib/loader.js?outputStyle=compressed&sourceMap!./src/scss/main.scss)
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/css-loader/dist/cjs.js):
ValidationError: CSS Loader Invalid Options

options should NOT have additional properties

    at validateOptions (c:\entradauno\entrada-uno-srl\webpack-starter-kit\node_modules\css-loader\node_modules\schema-utils\src\validateOptions.js:32:11)
    at Object.loader (c:\entradauno\entrada-uno-srl\webpack-starter-kit\node_modules\css-loader\dist\index.js:44:28)
    at runLoaders (c:\entradauno\entrada-uno-srl\webpack-starter-kit\node_modules\webpack\lib\NormalModule.js:301:20)
    at c:\entradauno\entrada-uno-srl\webpack-starter-kit\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at c:\entradauno\entrada-uno-srl\webpack-starter-kit\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at runSyncOrAsync (c:\entradauno\entrada-uno-srl\webpack-starter-kit\node_modules\loader-runner\lib\LoaderRunner.js:143:3)
    at iterateNormalLoaders (c:\entradauno\entrada-uno-srl\webpack-starter-kit\node_modules\loader-runner\lib\LoaderRunner.js:232:2)
    at iterateNormalLoaders (c:\entradauno\entrada-uno-srl\webpack-starter-kit\node_modules\loader-runner\lib\LoaderRunner.js:221:10)
    at c:\entradauno\entrada-uno-srl\webpack-starter-kit\node_modules\loader-runner\lib\LoaderRunner.js:236:3
    at context.callback (c:\entradauno\entrada-uno-srl\webpack-starter-kit\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at postcss.process.then (c:\entradauno\entrada-uno-srl\webpack-starter-kit\node_modules\postcss-loader\src\index.js:197:9)
 @ ./src/scss/main.scss 2:14-292
 @ ./src/index.js
 @ multi (webpack)-dev-server/client?http://localhost:8082 ./src
Child html-webpack-plugin for "index.html":
     1 asset
    Entrypoint undefined = index.html
    [./node_modules/html-webpack-plugin/lib/loader.js!./src/template.html] 299 bytes {0} [built]
Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js?minimize&sourceMap!node_modules/postcss-loader/src/index.js??ref--6-3!node_modules/sass-loader/lib/loader.js?outputStyle=compressed&sourceMap!src/scss/main.scss:
    Entrypoint mini-css-extract-plugin = *
    [./node_modules/css-loader/dist/cjs.js?minimize&sourceMap!./node_modules/postcss-loader/src/index.js?!./node_modules/sass-loader/lib/loader.js?outputStyle=compressed&sourceMap!./src/scss/main.scss] ./node_modules/css-loader/dist/cjs.js?minimize&sourceMap!./node_modules/postcss-loader/src??ref--6-3!./node_modules/sass-loader/lib/loader.js?outputStyle=compressed&sourceMap!./src/scss/main.scss 470 bytes {mini-css-extract-plugin} [built] [failed] [1 error]

    ERROR in ./src/scss/main.scss (./node_modules/css-loader/dist/cjs.js?minimize&sourceMap!./node_modules/postcss-loader/src??ref--6-3!./node_modules/sass-loader/lib/loader.js?outputStyle=compressed&sourceMap!./src/scss/main.scss)
    Module build failed (from ./node_modules/css-loader/dist/cjs.js):
    ValidationError: CSS Loader Invalid Options

    options should NOT have additional properties

        at validateOptions (c:\entradauno\entrada-uno-srl\webpack-starter-kit\node_modules\css-loader\node_modules\schema-utils\src\validateOptions.js:32:11)
        at Object.loader (c:\entradauno\entrada-uno-srl\webpack-starter-kit\node_modules\css-loader\dist\index.js:44:28)
i ｢wdm｣: Failed to compile.
`      {
        test: /\.(css|scss)$/,
        use: [
          "style-loader",
          MiniCssExtractPlugin.loader,
          "css-loader?minimize&sourceMap",
          {
            loader: "postcss-loader",
            options: {
              autoprefixer: {
                browser: ["last 2 versions"]
              },
              sourceMap: true,
              plugins: () => [autoprefixer]
            }
          },
          "sass-loader?outputStyle=compressed&sourceMap"
        ]
      }`

PARA ESTE ERROR LE TUVE QUE SACAR AL css-loader "css-loader**?minimize&sourceMap**", y al "sass-loader**?outputStyle=compressed&sourceMap**" lo que esta en negrita y me compilo bien la otra opcion es armarlo mas simple asi:

```
      {
         test: /\.(css|sass|scss)$/,
         use: [MiniCssExtractPlugin.loader, "css-loader", "sass-loader"]
       }
```
de esta forma compila bien Webpack

**Comment by MScevola** [comment]
> @juanitaV try `npm rebuild node-sass`

thanks

**Comment by yosraa** [comment]
> @juanitaV try `npm rebuild node-sass`

work  for me

**Comment by pierresis** [comment]
> @juanitaV try `npm rebuild node-sass`

Thanks, it works for me too :)
Don't forget to relaunch your app (npm start again)

**Comment by roclet** [comment]
npm rebuild node-sass

Worked for me Thank you a lot my bro

**Comment by OliveIT** [comment]
I had to remove `node_modules` folder and run `npm install`.
Cheers!

**Comment by SergiuMaja** [comment]
I experienced the same issue as @dongdongmao after upgrading to Angular 8 and it seems the node-sass dependency was coming from some other package (it wasn't added in package.json).
Just installing node-sass on it's own fixed the issue -> npm install node-sass

**Comment by SrikrushnaP** [comment]
Below command work for me
`npm install node-sass`
Thanks

**Comment by Abhishek2kr** [comment]
> npm rebuild node-sass

Run the command as administrator mode. (For whom `npm rebuild node-sass` not worked)

**Comment by budiselic** [comment]
> > npm rebuild node-sass
> 
> Run the command as administrator mode. (For whom `npm rebuild node-sass` not worked)

didnt worked for me

**Comment by mmrzk** [comment]
`npm rebuild node-sass` didn't work for me either, the interesting thing is that this error appeared out of blue without me even changing any config files, I just Ctrl+Z a few lines of code in a component (before everything worked even without those lines of code).

**Comment by mmrzk** [comment]
simply installing node-sass helped me, `npm i node-sass` (before that I also removed node_modules directory, but I'm not sure if it's necessary)

**Comment by alejoortiz18** [comment]
> @juanitaV intenta`npm rebuild node-sass`

gracias, eso me funcionó, excelente aporte

**Comment by ihatepoper** [comment]
[help me im newbie]

ERROR in ./resources/sass/app.scss
Module build failed (from ./node_modules/css-loader/index.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):

@import '~admin-lte/build/scss/aAdminLTE';
       ^
      Can't find stylesheet to import.
   ╷
11 │ @import '~admin-lte/build/scss/aAdminLTE';

**Comment by coopeu** [comment]
`yarn add node-sass` it isn't working

**Comment by younes0** [comment]
None of the solutions worked for me.
I use `style-loader` and it happened with `1.0` versions.
Reverting back to `"^0.23` fixed the problem.

**Comment by sjcraj** [comment]
check node & node-sass compatability.

NodeJS | Minimum node-sass version | Node Module
Node 13 | 4.13+ | 79
Node 12 | 4.12+ | 72
Node 11 | 4.10+ | 67
Node 10 | 4.9+ | 64
Node 8 | 4.5.3+ | 57

I changed the corresponding node-sass version to my nodeJs version. It worked

**Comment by charlesrajesh** [comment]
@sjcraj  thanks for the reference. it helped me.

**Comment by callowaylc** [comment]
Just wanted to note that "reinstalling" and/or "rebuilding" is a workaround, NOT A SOLUTION

**Comment by rust-rs** [comment]
Paste this to your `package.json`, this is a previous version of `sass-loader`

1. `"sass-loader": "^7.1.0"`

2. `npm install`

**Comment by Hyonta** [comment]
I've tried all of the above but still haven't solved with this error after ng build.

Module build failed (from ./node_modules/sass-loader/lib/loader.js):
    color: color($colors, text_gray);
                ^
      Undefined variable: "$colors".

**Comment by SrinivasM13** [comment]
same problem for me

**Comment by umair-murtaza** [comment]
I tried `npm install --save-dev webpack` and then `npm install --save-dev node-sass` and then `sudo npm rebuild node-sass` but still getting the same error

**Comment by zemunkh** [comment]
Not this one:

```
<style >
  @import './assets/scss/app.scss';
</style>
```

This importing format should be as follows. Don't forget add **lang="scss" scopded**
```
<style lang="scss" scoped>
  @import './assets/scss/app.scss';
</style>
```

**Comment by osmaircoelho** [comment]
Maybe its solve any problem

maybe the problem is **the order of loaders on webpack.config.js**  /\.vue$/ must come first, and so on.

try this
```

 module: {
    rules: [
      {
        test: /\.vue$/,
        loader: 'vue',
        options: {
          // vue-loader options go here
        }
      },
      {
        test: /\.js$/,
        loader: 'babel-loader',
        exclude: /node_modules/
      },
      {
        test: /\.(png|jpg|gif|svg)$/,
        loader: 'file-loader',
        options: {
          name: '[name].[ext]?[hash]'
        }
      },
      {
        test: /\.(woff|woff2|ttf|svg|eot)$/,
        loader: 'url-loader'
      }
    ]
  }
```

**Comment by jsafe00** [comment]
> Paste this to your `package.json`, this is a previous version of `sass-loader`
> 
> 1. `"sass-loader": "^7.1.0"`
> 2. `npm install`

this worked for me.. 
thanks

**Comment by floyd70s** [comment]
if you use python 3.7 you can have problems with the comand "npm install node-sass",  you can use this: "curl -o- -L https://yarnpkg.com/install.sh | bash" for install yarn and then execute: "yarn add node-sass"

i hope its work for u.
-sorry for my poor translation-

**Comment by del324** [comment]
npm i node-sass
solved my problem

**Comment by yazansalhi** [comment]
npm uninstall --save-dev sass-loader
npm install --save-dev sass-loader@7.1.0
solved my problem

**Comment by sidlexx** [comment]
> npm uninstall --save-dev sass-loader
> npm install --save-dev sass-loader@7.1.0
> solved my problem

worked for me ! thanks

**Comment by domicoder** [comment]
npm install node-sass --save-dev 
solved my problem

**Comment by Znerf** [comment]
In my cases, it worked when I used yarn install command instead of npm install

**Comment by dasler-fw** [comment]
If nothing works from what is written on top, i will show how i fix problem: "_(module build failed (from ./node_modules/sass-loader/dist/cjs.js)_".  My project **was created with 'create-react-app'** and i added **webpack.dev.js custom config**, and then i caught this problem with sass. **Solve**: just open your create-react-app webpack config, cut out css, css modules and 'getStyleLoaders' function from config:
![image](https://user-images.githubusercontent.com/33331165/85234318-31bcef80-b415-11ea-959b-ba3ee82c5752.png)
and put them to `module: {rules: [cssConfig, cssModulesConfig]}` **in 'webpack.dev.js' file** (your custom config): 
![image](https://user-images.githubusercontent.com/33331165/85234382-adb73780-b415-11ea-82e6-5bfca2f56d1b.png).
Rebuild your project 'npm start' and... enjoy.
Дала аьтто бойл массоа бусулбачу неха!

**Comment by RushabhBhalgat** [comment]
Nothing solved my problem yet please help

**Comment by equicy** [comment]
Nothing solved my problem yet please help, too

**Comment by Imad-MACHI** [comment]
I have just removed webpack, then reinstalled it again, and the problem was solved

**Comment by mohammadjavadnouri** [comment]
I have the same problem after trying all the above.

please, someone, take a snapshot of their package.json so I can change the versions to the appropriate ones.

**Comment by IsraelTorresFullSail** [comment]
For me work these steps:
1. $ rm -rf node_modules
2. $ npm ci
3. $ nvm install node
4. $ npm rebuild node-sass

**Comment by mohammadjavadnouri** [comment]
I don't remember what did I do, but now it works! =))))))))))))

**Comment by TheBigSteph** [comment]
> @juanitaV try `npm rebuild node-sass`

Thanks, that works for me

**Comment by rgurgul** [comment]
for me works only downgrade postcss-loader to v3: npm i postcss-loader@v3

**Comment by sivaraman-s** [comment]
> Re-installing webpack solved the issue for me.
> npm install --save-dev webpack

I tried installing webpack and got several errors, then I uninstalled this.
Now I got into huge mess  ):

**Comment by evilebottnawi** [comment]
Don't use `extract-text-webpack-plugin`, please migrate on `mini-css-extract-plugin`

**Comment by mohsenmhs** [comment]
I tried update node version and it works. 💯

**Comment by ismail-dinar** [comment]
> @juanitaV try `npm rebuild node-sass`

This worked  for me. Thanks 😊

**Comment by GoodJob** [comment]
> I have just removed webpack, then reinstalled it again with the latest version, and the problem was solved

how you did that?

**Comment by GoodJob** [comment]
The most unstable technology ever is webpack. Surprisingly crashy. If something crashes in my projects - 70% chance it's webpack.

**Comment by Catalin29Ro** [comment]
I have this issues , i cannot find any ways to fix it
I have M1 chip

ERROR in ./app/javascript/stylesheets/application.scss (./node_modules/css-loader/dist/cjs.js??ref--7-1!./node_modules/postcss-loader/src??ref--7-2!./node_modules/sass-loader/dist/cjs.js??ref--7-3!./app/javascript/stylesheets/application.scss)
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
Error: Node Sass does not yet support your current environment: OS X Unsupported architecture (arm64) with Unsupported runtime (93)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.14.1
    at module.exports (/Users/catalinmocanu/Work/tuprenotalo2/back_office/node_modules/node-sass/lib/binding.js:13:13)
    at Object.<anonymous> (/Users/catalinmocanu/Work/tuprenotalo2/back_office/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Function.Module._load (node:internal/modules/cjs/loader:828:14)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at getDefaultSassImpl (/Users/catalinmocanu/Work/tuprenotalo2/back_office/node_modules/sass-loader/dist/index.js:198:10)
    at Object.loader (/Users/catalinmocanu/Work/tuprenotalo2/back_office/node_modules/sass-loader/dist/index.js:80:29)

**Comment by alexander-akait** [comment]
> Error: Node Sass does not yet support your current environment: OS X Unsupported architecture (arm64) with Unsupported runtime (93)

Please migrate on `sass` from `node-sass`

**Comment by UmarKhan-123** [comment]
./node_modules/css-loader/dist/cjs.js??ref--5-oneOf-4-1!./node_modules/postcss-loader/src??postcss!./src/App.css

**Comment by Nabin0433** [comment]
./src/Style/style.scss (./node_modules/css-loader/dist/cjs.js??ref--5-oneOf-6-1!./node_modules/postcss-loader/src??postcss!./node_modules/resolve-url-loader??ref--5-oneOf-6-3!./node_modules/sass-loader/dist/cjs.js??ref--5-oneOf-6-4!./src/Style/style.scss)
Error: PostCSS plugin tailwindcss requires PostCSS 8.
Migration guide for end-users:
https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users

**Comment by saulwolfdev** [comment]
I recommend this environment width webpack 5 , beacuse i am used, postcss, sass, babel, etc

https://github.com/saulwolfdev/webpack-5

**Comment by Jihaneharimech** [comment]
Nothing solved my problem yet

**Comment by equicy** [comment]
已收到  我会尽快回复您

**Comment by naz-i-ya** [comment]
I am struggling with this too...
tried above all solutions but didnt work for me...

**Comment by deepchothani10** [comment]
Getting this error from yesterday, all of a sudden in the dev environment was working smoothly before that. Tried all of this, but still facing the same thing, any solution, please??

./src/Components/css/styles.scss (./node_modules/css-loader/dist/cjs.js??ref--5-oneOf-6-1!./node_modules/postcss-loader/src??postcss!./node_modules/resolve-url-loader??ref--5-oneOf-6-3!./node_modules/sass-loader/dist/cjs.js??ref--5-oneOf-6-4!./src/Components/css/styles.scss)
Unexpected token ?

**Comment by Jittojoyes98** [comment]
I too have this issue? Any fix for this?

**Comment by equicy** [comment]
已收到  我会尽快回复您

**Comment by KanhaiyaJayas** [comment]
./src/index.scss (./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[7].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[7].use[2]!./node_modules/resolve-url-loader/index.js??ruleSet[1].rules[1].oneOf[7].use[3]!./node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[7].use[4]!./src/index.scss)

**Comment by lance2k** [comment]
Remove sass first, then install it as dev dependency
1. npm uninstall sass or npm uninstall -g sass
2. npm install sass sass-loader --save-dev

This fix it for me

**Comment by Jittojoyes98** [comment]
The same situation,no change after trying.

**Comment by solomon-ayodele65** [comment]
if your're facing this error and it has to do with tailwind css styling, i'll suggest you do a search for the main error cause on your IDE and take the matches entirely off your code then restart the app. it worked for me

**Comment by UMHoai** [comment]
you can check installed extension .sass (only)

**Comment by equicy** [comment]
已收到  我会尽快回复您

**Comment by Youssef-Hd** [comment]
Hi,
I've faced the same error after going back to play around with an old project of mine, I've done a lot of searching and tried multiple different things but the only thing that actually worked for me was to "npm install --save-dev case-sensitive-paths-webpack-plugin".

**Comment by equicy** [comment]
已收到  我会尽快回复您

**Comment by BrankoSrokuca** [comment]
It solved my problem because I transferred that file from my tsk file where I dragged the colors to .scss and now everything works, it doesn't give me that error.

so try changing the file extension to .scss

**Comment by akanksha356** [comment]
./src/pages/auth/auth.module.scss (./node_modules/css-loader??ref--6-oneOf-6-1!./node_modules/postcss-loader/src??postcss!./node_modules/sass-loader/lib/loader.js??ref--6-oneOf-6-3!./src/pages/auth/auth.module.scss)
To import Sass files, you first need to install node-sass.
Run `npm install node-sass` or `yarn add node-sass` inside your workspace.

**Comment by wbisschoff** [comment]
This worked for me [(https://github.com/webpack-contrib/sass-loader/issues/530#issuecomment-565719388)]

Above comment worked for me....

It is the compatibility of the node-sass you are using - I was using 4.9 for an old project so downloaded and installed node 10.18.0 using NVM - Node Version Manager here - [https://www.freecodecamp.org/news/node-version-manager-nvm-install-guide]

> check node & node-sass compatability.
> 
> NodeJS | Minimum node-sass version | Node Module Node 13 | 4.13+ | 79 Node 12 | 4.12+ | 72 Node 11 | 4.10+ | 67 Node 10 | 4.9+ | 64 Node 8 | 4.5.3+ | 57
> 
> I changed the corresponding node-sass version to my nodeJs version. It worked

**Comment by equicy** [comment]
已收到  我会尽快回复您

**Comment by Nagendrak12** [comment]
ERROR in ./src/styles/experienceStyles.scss (./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[7].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[7].use[2]!./node_modules/resolve-url-loader/index.js??ruleSet[1].rules[1].oneOf[7].use[3]!./node_modules/react-scripts/node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[7].use[4]!./src/styles/experienceStyles.scss)
Module build failed (from ./node_modules/react-scripts/node_modules/sass-loader/dist/cjs.js):

having this issue i have done above all methods but its not worked for me

**Comment by jesuitdelray** [comment]
tried all above, but still have this error: 

Cannot read properties of undefined (reading 'indexOf')
node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[4].use[1]!./node_modules/sass-loader/dist/cjs.js!./src/app/styles/index.scss

**Comment by theoturner** [comment]
For those experiencing this problem recently, node LTS has updated from v18 to v20. This breaks legacy node-sass installs. Downgrading to node v18 fixed this for me.

**Comment by KamilMr** [comment]
@theoturner thanks. Using node v18 solved my issue.

**Comment by equicy** [comment]
已收到  我会尽快回复您

**Comment by tarikulker-js** [comment]
downgrading `react-script` to `^3.4.3` solved the issue for me. good luck!

**Comment by equicy** [comment]
已收到  我会尽快回复您

**Comment by LeulAria** [comment]
> 已收到  我会尽快回复您

what bro lol stop it

**Comment by LeulAria** [comment]
> 已收到  我会尽快回复您

Received I will reply to you as soon as possible
bot

**Comment by Sibusiso07** [comment]
Hi, non of the solutions have are working for me, here is the error that I am getting:

ERROR in ./src/App.scss (./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[9].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[9].use[2]!./node_modules/resolve-url-loader/index.js??ruleSet[1].rules[1].oneOf[9].use[3]!./node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[9].use[4]!./src/App.scss)
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
Undefined variable.
   ╷
12 │     padding: $bpk-spacing-lg * 2;
   │              ^^^^^^^^^^^^^^^
   ╵
  src\App.scss 12:14  root stylesheet

**Comment by GariBisht** [comment]
Angular Live Development Server is listening on localhost:4203, open your browser on http://localhost:4203/ **
 10% building modules 6/6 modules 0 activeℹ ｢wds｣: Project is running at http://localhost:4203/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: 404s will fallback to //index.html
                                                                                          
Date: 2024-04-12T10:30:08.821Z
Hash: 614a0725fa656f44500a
Time: 7424ms
chunk {main} main.js, main.js.map (main) 433 kB [entry] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 636 kB [entry] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 5.22 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 425 kB [entry] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 3.3 MB [initial] [rendered]

ERROR in ./src/styles.scss (./node_modules/raw-loader!./node_modules/postcss-loader/lib??embedded!./node_modules/sass-loader/dist/cjs.js??ref--14-3!./src/styles.scss)
Module build failed: Error: Node Sass version 9.0.0 is incompatible with ^4.0.0.
    at getRenderFuncFromSassImpl (/home/garima/Project/My-Angular-Project/angular-animation/node_modules/sass-loader/dist/index.js:165:13)
    at Object.loader (/home/garima/Project/My-Angular-Project/angular-animation/node_modules/sass-loader/dist/index.js:79:18)
ERROR in ./src/app/todo/todo.component.scss
Module build failed: Error: Node Sass version 9.0.0 is incompatible with ^4.0.0.
    at getRenderFuncFromSassImpl (/home/garima/Project/My-Angular-Project/angular-animation/node_modules/sass-loader/dist/index.js:165:13)
    at Object.loader (/home/garima/Project/My-Angular-Project/angular-animation/node_modules/sass-loader/dist/index.js:79:18)


Please suggest me some solution I applied all methods.

**Comment by ghost160111** [comment]
download node-sass 9.0.0 which is the last version, but it is recommended not to use node-sass, use just sass, because that worked for me, node-sass is deprecated package!

**Comment by ghost160111** [comment]
> Angular Live Development Server is listening on localhost:4203, open your browser on http://localhost:4203/ ** 10% building modules 6/6 modules 0 activeℹ ｢wds｣: Project is running at http://localhost:4203/ ℹ ｢wds｣: webpack output is served from / ℹ ｢wds｣: 404s will fallback to //index.html
> 
> Date: 2024-04-12T10:30:08.821Z Hash: 614a0725fa656f44500a Time: 7424ms chunk {main} main.js, main.js.map (main) 433 kB [entry] [rendered] chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 636 kB [entry] [rendered] chunk {runtime} runtime.js, runtime.js.map (runtime) 5.22 kB [entry] [rendered] chunk {styles} styles.js, styles.js.map (styles) 425 kB [entry] [rendered] chunk {vendor} vendor.js, vendor.js.map (vendor) 3.3 MB [initial] [rendered]
> 
> ERROR in ./src/styles.scss (./node_modules/raw-loader!./node_modules/postcss-loader/lib??embedded!./node_modules/sass-loader/dist/cjs.js??ref--14-3!./src/styles.scss) Module build failed: Error: Node Sass version 9.0.0 is incompatible with ^4.0.0. at getRenderFuncFromSassImpl (/home/garima/Project/My-Angular-Project/angular-animation/node_modules/sass-loader/dist/index.js:165:13) at Object.loader (/home/garima/Project/My-Angular-Project/angular-animation/node_modules/sass-loader/dist/index.js:79:18) ERROR in ./src/app/todo/todo.component.scss Module build failed: Error: Node Sass version 9.0.0 is incompatible with ^4.0.0. at getRenderFuncFromSassImpl (/home/garima/Project/My-Angular-Project/angular-animation/node_modules/sass-loader/dist/index.js:165:13) at Object.loader (/home/garima/Project/My-Angular-Project/angular-animation/node_modules/sass-loader/dist/index.js:79:18)
> 
> Please suggest me some solution I applied all methods.

download node-sass 9.0.0 which is the last version, but it is recommended not to use node-sass, use just sass, because that worked for me, node-sass is deprecated package!

**Comment by ghost160111** [comment]
> Angular Live Development Server is listening on localhost:4203, open your browser on http://localhost:4203/ ** 10% building modules 6/6 modules 0 activeℹ ｢wds｣: Project is running at http://localhost:4203/ ℹ ｢wds｣: webpack output is served from / ℹ ｢wds｣: 404s will fallback to //index.html
> 
> Date: 2024-04-12T10:30:08.821Z Hash: 614a0725fa656f44500a Time: 7424ms chunk {main} main.js, main.js.map (main) 433 kB [entry] [rendered] chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 636 kB [entry] [rendered] chunk {runtime} runtime.js, runtime.js.map (runtime) 5.22 kB [entry] [rendered] chunk {styles} styles.js, styles.js.map (styles) 425 kB [entry] [rendered] chunk {vendor} vendor.js, vendor.js.map (vendor) 3.3 MB [initial] [rendered]
> 
> ERROR in ./src/styles.scss (./node_modules/raw-loader!./node_modules/postcss-loader/lib??embedded!./node_modules/sass-loader/dist/cjs.js??ref--14-3!./src/styles.scss) Module build failed: Error: Node Sass version 9.0.0 is incompatible with ^4.0.0. at getRenderFuncFromSassImpl (/home/garima/Project/My-Angular-Project/angular-animation/node_modules/sass-loader/dist/index.js:165:13) at Object.loader (/home/garima/Project/My-Angular-Project/angular-animation/node_modules/sass-loader/dist/index.js:79:18) ERROR in ./src/app/todo/todo.component.scss Module build failed: Error: Node Sass version 9.0.0 is incompatible with ^4.0.0. at getRenderFuncFromSassImpl (/home/garima/Project/My-Angular-Project/angular-animation/node_modules/sass-loader/dist/index.js:165:13) at Object.loader (/home/garima/Project/My-Angular-Project/angular-animation/node_modules/sass-loader/dist/index.js:79:18)
> 
> Please suggest me some solution I applied all methods.

Like I said the best solution for this error, is deleting node-sass, if you have webpack configuration, configure correctly everything there, I mean loaders, that loads CSS, SASS, etc. And download just 'sass' package.

**Comment by azaeuoi** [comment]
If you mistakenly sent money to the wrong number on PhonePe, it is generally not possible to reverse the transaction directly through the app. However, you can contact PhonePe customer support 07602532123 as soon as possible to report the issue and request assistance in resolving the situation....

**Comment by equicy** [comment]
已收到  我会尽快回复您
