### ISSUE TITLE
Support for node-sass 6.0.0

### ISSUE THREAD

**Issue by doberkofler** [webpack-contrib/sass-loader#945]
### Feature Proposal

Support for the latest node-sass 6.0.0 and therefore also Node 16 would be most appreciated.

**Comment by Cikey** [comment]
We are currently using sass-loader v10 and fixed it for us by adding the new node-sass major version to the semver-check:

```javascript
} else if (implementationName === "node-sass") {
  if (!semver.satisfies(version, "^4.0.0 || ^5.0.0 || ^6.0.0")) {
    loaderContext.emitError(
      new Error(
        `Node Sass version ${version} is incompatible with ^4.0.0 || ^5.0.0 || ^6.0.0.`
      )
    );
  }
}
```
https://github.com/Cikey/sass-loader/compare/v10.1.1...Cikey:support-node-sass-6?expand=1

Im not sure if anything else needs to be checked, it works for our vue-cli project now.

**Comment by alexander-akait** [comment]
Yes, WIP, release will be in near future

**Comment by alexander-akait** [comment]
https://github.com/webpack-contrib/sass-loader/pull/948, do release

**Comment by alexander-akait** [comment]
Done https://www.npmjs.com/package/sass-loader under `version-10` tag

**Comment by DevonPeroutky** [comment]
Hey @alexander-akait Thanks for work to fix this! However, I'm still getting the following error:
```
Failed to compile.

./src/index.scss (./node_modules/react-scripts/node_modules/css-loader/dist/cjs.js??ref--6-oneOf-5-1!./node_modules/postcss-loader/src??postcss!./node_modules/resolve-url-loader??ref--6-oneOf-5-3!./node_modules/react-scripts/node_modules/sass-loader/dist/cjs.js??ref--6-oneOf-5-4!./src/index.scss)

Error: Node Sass version 6.0.0 is incompatible with ^4.0.0.
```

I'm on:
- node: v16.0.0
- node-sass: ^6.0.0
- sass-loader: 10.2.0

**Comment by alexander-akait** [comment]
Run `npm ls sass-loader`/`yarn why sass-loader`, always use this command to get actual version
